#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

if [[ -z "${ZSH_CACHE_DIR}" ]]; then
    echo "Install docker completions..."
    mkdir -p "${ZSH_CACHE_DIR}"/completions
    curl -L https://raw.githubusercontent.com/docker/cli/master/contrib/completion/zsh/_docker -o "$ZSH_CACHE_DIR"/completions/_docker
fi

